// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"notifications/internal/ctx"
	"notifications/repositories"
)

// Injectors from wire.go:

func Initialize() (*ctx.Handler, error) {
	gateway := repositories.NewGatewayRepository()
	handler := ctx.NewHandler(gateway)
	return handler, nil
}
